### ISSUE TITLE
Any support for typescript?

### ISSUE THREAD

**Issue by NetanelBasal** [planttheidea/crio#35]
I am working with Angular 2 and required support for typescript, there is any plans for this?

Thanks.

**Comment by chimon2000** [comment]
Would love to see this!

**Comment by planttheidea** [comment]
@NetanelBasal no plans for creating type declarations (either TypeScript or Flowtype) on the immediate roadmap, but I would not be opposed to it. I personally don't use TypeScript, so I'll happily accept a PR (or even advice about how I can create the definition).
